instances:
  - person
  - y
  - test_person
  - test_y

features:
  person:
    - Pregnancies
    - Glucose
    - BloodPressure
    - SkinThickness
    - Insulin
    - BMI
    - DiabetesPedigreeFunction
    - Age
  y:
    - Outcome

  test_person:
    - Pregnancies
    - Glucose
    - BloodPressure
    - SkinThickness
    - Insulin
    - BMI
    - DiabetesPedigreeFunction
    - Age
  test_y:
    - Outcome

train:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/train.csv
    batch_size: 32

validation:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/val.csv
    batch_size: 128

test:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/test.csv
    batch_size: 128


constants:
  - diabetes : 1
  - healthy : 0

predicates:
  Diabetic:
    args: [person]
    structure:
      type: feed-forward
      layers:
        - in: [person, 4 * person]
          activation: elu
        - hidden: [4 * person, 8 * person]
          activation: elu
        - hidden: [8 * person, 16 * person]
          activation: elu
        - hidden: [16 * person, 32 * person]
          activation: elu
        - hidden: [32 * person, 4 * person]
          activation: elu
        - out: [ 4 * person, 1]
          activation: sigmoid  
          
constraints:
  - all person. (y == diabetes -> Diabetic(person))
  - all person. (y == healthy -> not Diabetic(person)) 
  - all person. ( ( (person[BMI] < 26) and (person[Glucose] < 101 )) -> not Diabetic(person))
  - all person. ( ( (person[BMI] > 29) and (person[Glucose] > 125 )) -> Diabetic(person))
  - all person. ( ( (person[Glucose] > 143.5) and (person[DiabetesPedigreeFunction] > 0.32 )) -> Diabetic(person))
  - all person. ( ( (person[Glucose] > 143.5) and (person[DiabetesPedigreeFunction] <= 0.32) and (person[BMI] <= 31.40)) -> not Diabetic(person))
  - all person. ( ( (person[Glucose] > 143.5) and (person[DiabetesPedigreeFunction] <= 0.32) and (person[BMI] > 31.40)) -> Diabetic(person))
  - all person. (((person[Glucose] <= 143.5) and (person[Pregnancies] <= 7.5) and (person[BMI] <= 45.44)) -> not Diabetic(person))
  - all person. (((person[Glucose] <= 143.5) and (person[Pregnancies] <= 7.5) and (person[BMI] > 45.44)) -> Diabetic(person))
  - all person. (((person[Glucose] <= 143.5) and (person[Pregnancies] > 7.5) and (person[DiabetesPedigreeFunction] > 0.50)) -> Diabetic(person))
  - all person. (((person[Glucose] <= 143.5) and (person[Pregnancies] > 7.5) and (person[DiabetesPedigreeFunction] <= 0.50) and (person[BloodPressure] <= 91.0)) -> not Diabetic(person))
  - all person. (((person[Glucose] <= 143.5) and (person[Pregnancies] > 7.5) and (person[DiabetesPedigreeFunction] <= 0.50) and (person[BloodPressure] > 91.0)) -> Diabetic(person))

unused:
