instances:
  - person
  - y
  - test_person
  - test_y

features:
  person:
    - Pregnancies
    - Glucose
    - BloodPressure
    - SkinThickness
    - Insulin
    - BMI
    - DiabetesPedigreeFunction
    - Age
  y:
    - Outcome

  test_person:
    - Pregnancies
    - Glucose
    - BloodPressure
    - SkinThickness
    - Insulin
    - BMI
    - DiabetesPedigreeFunction
    - Age
  test_y:
    - Outcome


data:
  train:
    instances: [person]
    targets: [y]
    path: datasets/train.csv
    batch_size: 32

  test:
    instances: [test_person]
    targets: [test_y]
    path: datasets/test.csv
    batch_size: 128

constants:
  - diabetes : 1
  - healthy : 0

predicates:
  Classifier:
    args: [person]
    structure:
      type: feed-forward
      layers:
        - in: [person, 4 * person]
          activation: elu
        - hidden: [4 * person, 4 * person]
          activation: elu
        - out: [ 4 * person, 1]
          activation: sigmoid  
          
constraints:
  - all person. (y == diabetes -> Classifier(person))
  - all person. (y == healthy -> not Classifier(person)) 
  - all person. ( ((person[BMI] < 26) and (person[Glucose] < 101)) -> not Classifier(person))
  - all person. ( ((person[BMI] > 29) and (person[Glucose] > 125)) -> Classifier(person))
