instances:
  - person
  - y

features:
  person:
    - Pregnancies
    - Glucose
    - BloodPressure
    - SkinThickness
    - Insulin
    - BMI
    - DiabetesPedigreeFunction
    - Age
  y:
    - Outcome

data:
  binary:
    instances: [person]
    targets: [y]
    path: datasets/pima_indians_imputed.csv
    batch_size: 128

constants:
  - diabetes : 1
  - healthy : 0

predicates:
  Classifier:
    args: [person]
    structure:
      type: feed-forward
      layers:
        - in: [person, 8 * person]
          activation: elu
        - hidden: [8 * person, 16 * person]
          activation: elu
        - hidden: [16 * person, 8 * person]
          activation: elu
        - out: [ 8 * person, 1]
          activation: sigmoid  
          
constraints:
  - all person. (y == diabetes -> Classifier(person))
  - all person. (y == healthy -> not Classifier(person)) 
  - all person. ( ((person[BMI] < 26) and (person[Glucose] < 101)) -> not Classifier(person))
  - all person. ( ((person[BMI] > 29) and (person[Glucose] > 125)) -> Classifier(person))
