instances:
  - person
  - y

features:
  person:
    - Pregnancies
    - Glucose
    - BloodPressure
    - SkinThickness
    - Insulin
    - BMI
    - DiabetesPedigreeFunction
    - Age
  y:
    - Outcome

train:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/train.csv
    batch_size: 32

validation:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/val.csv
    batch_size: 128

test:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/test.csv
    batch_size: 128

constants:
  - diabetes : 1
  - healthy : 0

predicates:
  Diabetic:
    args: [person]
    structure:
      type: feed-forward
      layers:
        - in: [person, 64] 
          activation: relu
          regularization: 
            - dropout: 0.04058443799610505
            - batch_norm: True

        - hidden: [64, 128]
          activation: relu
          regularization: 
            - dropout: 0.04058443799610505
            - batch_norm: True

        - out: [128, 1]
          activation: sigmoid

          
constraints:
  - rule: "all person. (y == diabetes -> Diabetic(person))"
  - rule: "all person. (y == healthy -> not Diabetic(person))"

  - rule: "all person. (((person[BMI] < 26) and (person[Glucose] < 101 )) -> not Diabetic(person))"
  - rule: "all person. (((person[BMI] > 29) and (person[Glucose] > 125 )) -> Diabetic(person))"

  - rule: "all person. (((person[Glucose] > 143.5) and (person[DiabetesPedigreeFunction] > 0.32 )) -> Diabetic(person))"
  - rule: "all person. (((person[Glucose] > 143.5) and (person[DiabetesPedigreeFunction] <= 0.32) and (person[BMI] > 31.40)) -> Diabetic(person))"
  - rule: "all person. (((person[Glucose] > 143.5) and (person[DiabetesPedigreeFunction] <= 0.32) and (person[BMI] <= 31.40)) -> not Diabetic(person))"

  - rule: "all person. (((person[Glucose] <= 143.5) and (person[Pregnancies] > 7.5) and (person[DiabetesPedigreeFunction] > 0.50)) -> Diabetic(person))"
  - rule: "all person. (((person[Glucose] <= 143.5) and (person[Pregnancies] <= 7.5) and (person[BMI] > 45.44)) -> Diabetic(person))"
  - rule: "all person. (((person[Glucose] <= 143.5) and (person[Pregnancies] <= 7.5) and (person[BMI] <= 45.44)) -> not Diabetic(person))"
  
  - rule: "all person. (((person[Glucose] <= 143.5) and (person[Pregnancies] > 7.5) and (person[DiabetesPedigreeFunction] <= 0.50) and (person[BloodPressure] > 91.0)) -> Diabetic(person))"
  - rule: "all person. (((person[Glucose] <= 143.5) and (person[Pregnancies] > 7.5) and (person[DiabetesPedigreeFunction] <= 0.50) and (person[BloodPressure] <= 91.0)) -> not Diabetic(person))"
