instances:
  - person
  - y

features:
  person:
    - Pregnancies
    - Glucose
    - BloodPressure
    - SkinThickness
    - Insulin
    - BMI
    - DiabetesPedigreeFunction
    - Age
  y:
    - Outcome

train:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/train.csv
    batch_size: 32

validation:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/val.csv
    batch_size: 128

test:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/test.csv
    batch_size: 128

constants:
  - diabetes : 1
  - healthy : 0

predicates:
  Diabetic:
    args: [person]
    structure:
      type: feed-forward
      layers:
        - in: [person, 64] 
          activation: relu
          regularization: 
            - dropout: 0.04058443799610505
            - batch_norm: True

        - hidden: [64, 128]
          activation: relu
          regularization: 
            - dropout: 0.04058443799610505
            - batch_norm: True

        - out: [128, 1]
          activation: sigmoid
          
constraints:
  - rule: "all person. (y == diabetes -> Diabetic(person))"
  - rule: "all person. (y == healthy -> not Diabetic(person))"


