instances:
  - x

features:
  x:
    - in: feature1
    - in: feature2

constants:
  - pos : 1
  - neg : 0

predicates:
  Classifier:
    args:
      - in: x
    structure:
      type: feed-forward
      layers:
        - in: [x, 8 * x]
          activation: elu
        - hidden: [8 * x, 8 * x]
          activation: elu
        - out: [ 8 * x, 1]
          activation: sigmoid  
          
constraints: 
  - all x. (y == pos -> Classifier(x))
  - all x. (y == neg -> not Classifier(x))
