instance:
  - flower
  - class 

features:
  flower:
    - sepal_length
    - sepal_width
    - petal_length
    - petal_width
  class:
    - species

data:
  multi:
    instances: [flower]
    targets: [class]
    path: datasets/iris_training.csv
    batch_size: 32

constants:
  - setosa : 0
  - versicolor : 1
  - virginica : 2
  - zero : [1,0,0]
  - one : [0,1,0]
  - two: [0,0,1]

predicates:
  Iris:
    args: [flower]
    structure:
      type: feed-forward
      layers:
        - in: [flower, 4 * flower]
          activation: elu
        - hidden: [4 * flower, 4 * flower]
          activation: elu
        - hidden: [4 * flower, 2 * flower]
          activation: elu
        - out: [ 2 * flower, 3]
          activation: softmax 

constraints: 
- all flower. ((y == setosa) -> Iris(flower, zero))
- all flower. ((y == virginica) -> Iris(flower, one))
- all flower. ((y == versicolor) -> Iris(flower, two))