instance:
  - flower
  - species 

features:
  flower:
    - sepal_length
    - sepal_width
    - petal_length
    - petal_width
  species:
    - species

train:
  multi:
    instances: [flower]
    targets: [species]
    path: datasets/iris_training.csv
    batch_size: 32

constants:
  - setosa : 0
  - versicolor : 1
  - virginica : 2

predicates:
  Iris:
    args: [flower]
    structure:
      type: feed-forward
      layers:
        - in: [flower, 4 * flower]
          activation: elu
        - hidden: [4 * flower, 4 * flower]
          activation: elu
        - hidden: [4 * flower, 2 * flower]
          activation: elu
        - out: [ 2 * flower, 3]
          activation: softmax 

constraints: 
- rule: all flower. Iris(flower, output)
- rule: all flower. ((species == setosa) -> output[0])
- rule: all flower. ((species == versicolor) -> output[1])
- rule: all flower. ((species == virginica) -> output[2])