instance:
  - x

features:
  x:
    - in: feature1
    - in: feature2
    - out: class

predicates:
    Regressor:
      args:
        - in: x
        - out: prob
      structure:
        type: feed-forward
        layers:
          in: x 
          hidden: [hidden_layer_1, hidden_layer_2]
          out: prob

constraints: 
- "forall x. (y = Regressor(x))"