instances:
  - person
  - y

features:
  person:
    - Pregnancies
    - Glucose
    - BloodPressure
    - SkinThickness
    - Insulin
    - BMI
    - DiabetesPedigreeFunction
    - Age
  y:
    - Outcome

train:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/train.csv
    batch_size: 32

validation:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/val.csv
    batch_size: 32

test:
  medical:
    instances: [person]
    targets: [y]
    path: datasets/test.csv
    batch_size: 32
  
constants:
  - diabetes : 1
  - healthy : 0

predicates:
  Diabetic:
    args: [person]
    structure:
      type: feed-forward
      layers:
        - in: [person, 256] 
          activation: leaky_relu
          regularization: 
            - batch_norm: True

        - hidden: [256, 128]
          activation: leaky_relu
          regularization: 
            - batch_norm: True

        - hidden: [128, 64]
          activation: leaky_relu
          regularization: 
            - batch_norm: True

        - out: [64, 1]
          activation: sigmoid


          
constraints:
  - rule: "all person. (y == diabetes -> Diabetic(person))"
    weight: 2

  - rule: "all person. (y == healthy -> not Diabetic(person))"

  - rule: "all person. (((person[BMI] > 29) and (person[Glucose] > 125 )) -> Diabetic(person))"
    weight: 2
    
  - rule: "all person. (((person[BMI] < 26) and (person[Glucose] < 101 )) -> not Diabetic(person))"


